//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Bets = new HashSet<Bet>();
            this.Notifications = new HashSet<Notification>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DueDateTime { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<System.Guid> SellerId { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public Nullable<System.Guid> FeatureId { get; set; }
        public Nullable<decimal> MinBet { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<System.Guid> BuyerId { get; set; }
        public Nullable<System.Guid> HighestBetId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual Bet Bet { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
