//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid Id { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public Nullable<System.Guid> ReceiverId { get; set; }
        public Nullable<byte> NotificationTypeId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual NotificcationType NotificcationType { get; set; }
        public virtual Item Item { get; set; }
    }
}
